### ISSUE TITLE
.scrutinizer.yml

### ISSUE THREAD

**Issue by tanmillet** [tanmillet/note#26]
```
tools:
    # external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    # php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=tanmillet-coverage-file
                coverage:
                    file: tanmillet-coverage-file
                    format: php-clover
```
